# Generated by Django 2.2.3 on 2019-10-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20191010_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myimg',
            field=models.ImageField(null=True, upload_to='images\\'),
        ),
    ]
