# Generated by Django 2.2.3 on 2019-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_profile_myimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myresume',
            field=models.FileField(null=True, upload_to='doc\\'),
        ),
    ]
