# Generated by Django 2.2.3 on 2019-10-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20191010_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='myimg',
            field=models.ImageField(blank=True, null=True, upload_to='images\\'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='myresume',
            field=models.FileField(blank=True, null=True, upload_to='doc\\'),
        ),
    ]
